### ISSUE TITLE
Include map in new html setup?

### ISSUE THREAD

**Issue by lakegame** [lakegame/lakegame.github.io#2]
Hey @g-madden - I didn't read your original comments carefully enough, so I didn't realize regenerating the html from Rmd would overwrite your changes. Would there be a way to include the map again without doing that?
I'll revert my last commit.

**Comment by g-madden** [comment]
Yeah I can add the map a different way. Will probably have time for that on wednesday 😊

**Comment by lakegame** [comment]
Sweet, thanks!
